### Максимум в массиве

In [1]:
N=[4, 6, 2, 5, 3, 1]

In [2]:
max(N)

6

### Матрица симметрична

In [ ]:
matrix = [[1,2], [2,1]]

In [ ]:
1  2  3  5
*  3  4  6
*  *  6  1
*  *  *  5

In [11]:
def matrix_nums(matrix):
    for i in range(len(matrix)):
        for j in range(i):
            print(matrix[i][j],matrix[j][i])
            if matrix[i][j]!=matrix[j][i]:
                return 'no'
    return 'yes'

In [12]:
matrix_nums(matrix)

2 2


'yes'

### Максимум в матрице

In [ ]:

def matrix_nums(matrix):
    max_num = 0
    i=0
    j=0
    for i in range(m):
        for j in range(n):
            if matrix[i][j] > max_num:
                max_num = matrix[i][j]
    return max_num, i, j

In [44]:
def matrix_nums(matrix):
    max_num = None
    max_i = 0
    max_j = 0
    
    m = len(matrix)
    n = len(matrix[0])
    for i in range(m):
        for j in range(n):
            if (max_num is None) or (matrix[i][j] >= max_num):
                max_num = matrix[i][j]
                max_i = i
                max_j = j
    return max_num, max_i, max_j

In [8]:
matrix = [[1,2], [2,1]]

In [46]:
matrix_nums(matrix)

(4, 3, 3)

In [58]:
##test
import numpy as np
for i in range(1,10):
    matrix=np.random.randint(10, size=(i, i))
    num = matrix_nums(matrix)[0]
    mat_flattened = matrix.flatten()
    assert num==max(mat_flattened), num

### Строки в книге

In [42]:
K = int(input())
N = int(input())

def lines_and_pages(K,N):
    n = (N//K)+1   #номер страницы
    p = (N-1)%K + 1  #номер строки на странице
    
    return f"{n} {p}"

result = lines_and_pages(K,N)
print (result)

In [43]:
lines_and_pages(50, 1)

(1, 1)

### Количество учащихся

In [45]:
from math import *

In [65]:
def cnt_desks(c1, c2, c3):
    cls1 = c1//2 + c1%2
    cls2 = c2//2 + c2%2
    cls3 = c3//2 + c3%2
    
    return cls1 + cls2 + cls3

In [72]:
cnt_desks(20,21,22)

32

In [78]:
##test
import numpy as np
import random
from math import *
for i in range(0,10):
    cls1 = random.randint(1,27)
    cls2 = random.randint(1,27)
    cls3 = random.randint(1,27)

    diff = ceil(cls1/2)+ceil(cls2/2)+ceil(cls3/2)
    
    assert cnt_desks(cls1, cls2, cls3) == diff, (cls1,cls2,cls3)

### Циклически вправо

In [35]:
from random import randrange
N=5
mass = [randrange(10) for i in range(N)]

In [38]:
def move_right(N,mass):
    print(mass)
    for i in range(1,N):
        mass[-i], mass[-i-1] = mass[-i-1], mass[-i]
    
    return mass

In [5]:
move_right(N, mass)

[8, 7, 3, 9, 3]


([8, 7, 3, 9, 3], [3, 8, 7, 3, 9])

### Ваня наблюдает за лягушкой

In [33]:
K=int(input())
T=int(input())

7
8


In [32]:
def frog_looking(K,T):
    if K>=T:
        x = T
    else:
         x = (2*K)%T
    return x

In [34]:
frog_looking(K,T)

6

### Треугольник Паскаля

In [97]:
N = int(input())
M = int(input())
P = np.zeros((N,M))

3
3


In [98]:
for i in range(N):
    for j in range(M):
        P[i][0] = 1
        P[0][j] = 1;
        P[i][j] = P[i - 1][j] + P[i][j - 1]

In [100]:
print(P)

[[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 6.]]


In [99]:
P

array([[1., 1., 1.],
       [1., 2., 3.],
       [1., 3., 6.]])

In [ ]:
row = [sum(x) for x in zip([0]+row, row+[0])]